name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: read-all

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libdbus-1-dev \
            libsecret-1-dev \
            libxkbcommon-dev \
            libpulse-dev \
            libwayland-dev \
            libinput-dev \
            libudev-dev \
            libseat-dev \
            libexpat1-dev

      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

      - name: Install cargo-nextest
        uses: taiki-e/install-action@8e6bcdad38b75e3ed7b36872031a94f7c61006cc # cargo-nextest

      - name: Build
        run: cargo build --verbose

      - name: Check/sanitize
        run: just check

      - name: Run tests (applet + standalone)
        run: just test-matrix
