name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: read-all

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libdbus-1-dev \
            libsecret-1-dev \
            libxkbcommon-dev \
            libpulse-dev \
            libwayland-dev \
            libinput-dev \
            libudev-dev \
            libseat-dev \
            libexpat1-dev

      - name: Install just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2

      - name: Install cargo-nextest
        uses: taiki-e/install-action@8e6bcdad38b75e3ed7b36872031a94f7c61006cc # cargo-nextest

      - name: Build
        run: cargo build --verbose

      - name: Check/sanitize
        run: just check

      - name: Run tests (applet + standalone)
        run: just test-matrix
